### ISSUE TITLE
Network issues making the program unusable

### ISSUE THREAD

**Issue by kyngs** [cryinkfly/Autodesk-Fusion-360-for-Linux#330]
**Describe the bug**
Sometimes, when opening, I am greeted with this message:
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/38181667/a4e42098-3e8c-4a28-888d-8c243f72a3ea)

After clicking "Trust Anyway" I enter a very weird F360. Errors I've noticed:
- I cannot download read-only documents, for some reason, I can open editable ones just fine.
- I can save files, but they don't get uploaded to the cloud. They constantly appear as being uploaded.
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/38181667/4959b3dd-5cdf-48a8-8944-0d655e12b8a9)
- When I restart Fusion, the files I attempted to save earlier can't now be opened and are forever loading. 
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/38181667/ae80860f-e33f-49f7-9a65-a0199bf2315d)

**To Reproduce**
1. Install via the script
2. Run F360
3. Observe the issues

**Expected behavior**
Everything works.

**Desktop (please complete the following information):**
- The version number of Autodesk Fusion 360 - The launcher says: System Build-Version: 2.0.15509
- Graphics card model + Graphics card driver (Version number) - AMD Radeon RX 7900 XTX (radv 23.1.0)
- Operating system - Arch Linux
- Desktop environment - KDE 5.27.5
- DXVK- or OpenGL-Mode - Happens in both.

**Additional context**
After searching the logs, I've found some things that could be relevant to my issue:
```
21:39:37 [rpcHandler]: Receiving command setOnlineState
21:39:37 Received event setOnlineState, onlinsState: 0
21:39:37 [rpcHandler]: Receiving command triggerMigration
0958:fixme:winsock:setsockopt Unknown IPPROTO_TCP optname 0x00000003
21:39:38 Call to handler triggerMigration failed: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.253.153.36:443 - Local (u
ndefined:undefined). SDKError: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined)
.
    at RequestRunner.executeQuery (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:285313)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SDKCore.get (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:236555)
    at async Object.triggerMigration [as handler] (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3833977)
    at async rpcServiceSocketCallback (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3856346)
    at async C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3859717
    at async WsAdaptor.handleIncomingRequest (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3937743)
    at async WsAdaptor.handleMessage (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3937225)
    at async C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3935733
Caused by JournalError: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined).
    at tryFn (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:928315)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async QueryExecutor.executeOnServer (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:906199)
Caused by Object: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined)
    at internalConnect (net.js:934:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1077:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8)
21:39:38 SDKError: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined).
    at RequestRunner.executeQuery (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:285313)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SDKCore.get (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:236555)
    at async Object.triggerMigration [as handler] (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3833977)
    at async rpcServiceSocketCallback (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3856346)
    at async C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3859717
    at async WsAdaptor.handleIncomingRequest (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3937743)
    at async WsAdaptor.handleMessage (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3937225)
    at async C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3935733
Caused by JournalError: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined).
    at tryFn (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:928315)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async QueryExecutor.executeOnServer (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:906199)
Caused by Object: connect UNKNOWN 34.253.153.36:443 - Local (undefined:undefined)
    at internalConnect (net.js:934:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1077:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8)
21:39:38 [rpcHandler]: Receiving command setProxy
21:39:38 Disabling proxy
```
Later once again:
```
21:39:58 Could not get hub gmail1762193: Error: [ft-client]: Failed to fetch Hub info. tenantId: 17136612, impersonateUserid: undefined, baseUrl:https://gmail1762193.autodesk360.com, url:/l
ogin/api/hubs/17136612, status:undefined, data:undefined
21:39:58 Space collection id is : co.M0uiT-BGTX-FmQIx6vQvng
21:39:58 [rpcHandler]: Receiving command triggerMigration
21:39:58 [documentIdentityService]: Successfully rehydrated service.
     Space Collection id: co.M0uiT-BGTX-FmQIx6vQvng
0958:fixme:winsock:setsockopt Unknown IPPROTO_TCP optname 0x00000003
21:39:59 Call to handler triggerMigration failed: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.254.43.176:443 - Local (u
ndefined:undefined). SDKError: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 34.254.43.176:443 - Local (undefined:undefined)
```
```
21:39:59 Starting synchronization for space-collection co.M0uiT-BGTX-FmQIx6vQvng
0958:fixme:winsock:setsockopt Unknown IPPROTO_TCP optname 0x00000003
21:39:59 Synchronization for space collection co.M0uiT-BGTX-FmQIx6vQvng failed: An error has occurred while fetching data. There are likely more details available.
0958:fixme:winsock:setsockopt Unknown IPPROTO_TCP optname 0x00000003
```
```
21:41:10 [documentIdentityService]: PIM is disabled for this hub. Skipping
        serializing state. Space Collection id: co.M0uiT-BGTX-FmQIx6vQvng
21:41:10 --------------------------------------------------------------------------------
21:41:10 [documentSaved]: Start
21:41:10 An error occured while running the operation documentPostSaveExecutor: Space collection is disabled: [object Object] Error: Space collection is disabled
    at executeQueuedEvent (C:\Program Files\Autodesk\webdeploy\production\aa5acb965e635aafefbe0657ed470ebc997e829c\FremontJsLib\lib.fremont.nodejs.js:2:3850282)
21:41:10 {
  name: 'Worker-documentSaved',
  message: 'Space collection is disabled'
}
21:41:10 [documentSaved] PimStateService: ERROR - RPC queue operation failed [Space collection is disabled: [object Object]].
      Disabling PIM operations on document id: aafda137-3490-4351-894f-0391e7ff880e
21:41:10 [documentSaved]: End (2 ms)
21:41:10 --------------------------------------------------------------------------------
```
Later the same thing (^) once again. When shutting down f360, the message above appears like 20x (I suppose once for each of my models?)

Even though it appears that f360 just simply can not reach Autodesk servers, the network test passes just fine.
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/38181667/eb92cd9a-6161-4d6b-b563-01ff2546ef47)

Now browsing the logs provided by f360, I see the following info:
```
20230525T220055 I    888 [pim.core] GlobalReportError: Unexpected Journal Error while executing query: Request failed after 1 attempt(s). With error: connect UNKNOWN 54.220.164.67:443 - Local (undefined:undefined).
... stacktrace
name: 'SDKError',
  innerError: {
    code: JournalErrorCode {
      id: 'L7_GEN_DOWNSTREAM_ERROR',
      description: 'Something went wrong calling a downstream service.'
    },
    innerError: {
      errno: -4094,
      code: 'UNKNOWN',
      syscall: 'connect',
      address: '54.220.164.67',
      port: 443,
      config: {
        transitional: [Object],
        adapter: [Function: httpAdapter],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function (anonymous)],
        headers: [Object],
        httpAgent: [Agent],
        httpsAgent: [Agent],
        proxy: false,
        retries: 10,
        retriesInterval: 100,
        maximumRetriesInterval: 60000,
        exponentialBackOff: true,
        retryCodes: [Array],
        retryErrors: [Array],
        noRetryCodes: [],
        throwIfNotSuccess: true,
        getBearerToken: [Function: getBearerToken],
        baseURL: 'https://developer.api.autodesk.com/assetgraph/v1',
        keepAlive: true,
        socketTimeout: 60000,
        url: 'collections/co.M0uiT-BGTX-FmQIx6vQvng',
        method: 'get',
        params: [Object],
        data: undefined
      },
      isAxiosError: true,
      toJSON: [Function: toJSON],
      stack: 'Error: connect UNKNOWN 54.220.164.67:443 - Local (undefined:undefined)\n' +
```

**Comment by stotes** [comment]
I'm also having the same issue

**Comment by kyngs** [comment]
Well, I'm probably going to set up a VM until this is resolved because I need to use it kinda urgently.

**Comment by aiurlano** [comment]
I am also having this problem.
I think I was able to get rid of the server verification warning by using winecfg to add a native override for the library bcrypt.dll, but I am still unable to upload the files to cloud, making it pretty useless, unfortunately.
Any ideas?

**Comment by Reaper35** [comment]
I had this exact problem once now. I only use Fusion 360 since a bit over a week, so it worked before. Restart didn't fix it. I could - seemingly - solve it by going into Offline Mode and then back online.
I am running F360 thru Heroic with Proton GE, as described in #328.
But I also had and still have problems with saving my projects but this might be not Linux related (as someone else has the same/similar problem, described in Autodesk forums.)

**Comment by kyngs** [comment]
> I had this exact problem once now. I only use Fusion 360 since a bit over a week, so it worked before. Restart didn't fix it. I could - seemingly - solve it by going into Offline Mode and then back online. I am running F360 thru Heroic with Proton GE, as described in #328. But I also had and still have problems with saving my projects but this might be not Linux related (as someone else has the same/similar problem, described in Autodesk forums.)

Considering we're all experiencing it here, it's most likely a linux issue. I will probably continue using F360 in a Windows VM until this is resolved.

**Comment by kyngs** [comment]
@cryinkfly considering you're still pushing patches, are you not experiencing this issue?

**Comment by Reaper35** [comment]
> Considering we're all experiencing it here, it's most likely a linux issue. I will probably continue using F360 in a Windows VM until this is resolved.
Oh, sorry. I clarified the - supposedly - other issue a bit more in my previous post: Saving and does work, but not always. Someone else had same issue reported on Autodesk forums, he didn't mention Linux tho. Error messages (in console) seem to be the same as this persons ones.
But you are right, it could be the same root cause.

**Comment by aedancullen** [comment]
I am not experiencing this exact issue, though the server verification prompt indeed appears. If you haven't yet, I'd try completely disabling that verification in Preferences to see if it resolves anything for you - perhaps it is nothing more than an automatic "trust anyway" choice, or perhaps something else changes internally. I further disabled the "data transfer acceleration" feature, which the tooltip mentions can be a cause of upload/download issues. Of course, this is just shot-in-the-dark stuff prior to a complete understanding of what is going on.

![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/23391273/17497682-ca95-4701-8551-ed821cad50e4)

**Comment by cryinkfly** [comment]
I suspect it's due to disabling SSO authentication for login, which is likely to affect other Fusion 360 features as well. However, I will rebuild the launcher in the next few days/weeks so that the SSO authentication is only deactivated when logging in for the first time.

**Comment by Vermoot** [comment]
Unfortunately for me toggling offline/online doesn't solve the issue. After a while, I can't save files anymore, and if I haven't saved in the past 30 minutes.... well I guess that's on me but that work is lost.

Is there any other fix that could work? Keeping my file open as long as I can so I can avoid losing my work.
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/23317434/93bc261e-f184-4092-a912-e51b38925793)

**Comment by cryinkfly** [comment]
Any new news here?

**Comment by kyngs** [comment]
Idk, I can no longer replicate
